name: CI

on:
    push:
        paths:
            - "jellyclean/**"
        branches:
            - main
    pull_request:
        paths:
            - "jellyclean/**"
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: ./jellyclean
        steps:
            - uses: actions/checkout@v4
            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                  python-version: "3.13.1"
            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt
            - name: Run black
              run: black . --check
            - name: Run tests
              run: pytest
